### PR TITLE
TB68 WL API

### PR DESCRIPTION
**Pull request by jobisoft**
This is step one, transitioning to the WL API. I took care of overlayed load events and the patching (which now needs to be undone on unload). This needs now some testing from someone who knows how to use it.

It is still TB68. Moving to TB78 if everything is working out.

### CODE REVIEW

**Comment by sphh** [comment]
Thanks @jobisoft for helping out here! That's really great. I'll give it a try and report back, but please give me some time.

**Comment by jobisoft** [comment]
Sure, no hurry.

**Comment by sphh** [comment]
I just downloaded it from your repository, made and installed the `.xpi` file.

Starting TB 68, I get the following messages:
```log
WebExtensions: Loading packed extension from /home/sph/.thunderbird/h12df7pq.default/extensions/tblatex@xulforum.org.xpi ext-legacy.js:157
WebExtensions: Loading add-on preferences from  /home/sph/.thunderbird/h12df7pq.default/extensions/tblatex@xulforum.org.xpi ext-legacy.js:190
WebExtensions: Firing profile-after-change listeners for tblatex@xulforum.org ext-legacy.js:194
```
but when I insert a formula into the compose window and click `Latex It!` I get the following error messages:
```log
ReferenceError: tblatex is not defined messengercompose.xul:1:1
    onclick chrome://messenger/content/messengercompose/messengercompose.xul:1
ReferenceError: tblatex is not defined messengercompose.xul:1:1
    oncommand chrome://messenger/content/messengercompose/messengercompose.xul:1
```

The other option is to open a dialog window and insert your LaTeX equation there. This does not work at all:
```log
ReferenceError: tblatex is not defined messengercompose.xul:1:1
    onclick chrome://messenger/content/messengercompose/messengercompose.xul:1
    displayBirthdayList chrome://cardbook/content/birthdays/ovl_birthdays.js:57
    onShowPopup chrome://cardbook/content/birthdays/ovl_birthdays.js:77
    onLoad chrome://cardbook/content/birthdays/ovl_birthdays.js:44
    notify chrome://cardbook/content/cardbookSynchronization.js:2051
```

You can test it yourself, even if you don't have LaTeX installed (without LaTeX installed you should get an error message displayed in the message compose window):

1. Open a compose window in HTML mode, enter `$E=mc^2$` and press the `Latex It!` button (which might have to be added to the toolbar).
2. Open a compose window in HTML mode, get the pull-down menu from `Latex It!` displayed and choose `Insert complex LaTeX` and a dialog box should open. If successful, replace `__REPLACE_ME__` with `$E=mc^2$ and press `Insert at cursor position`.

BTW the conflicts with `content/main.js` is, because in the meanwhile we updated the add-on to get rid of some bugs (and possibly inserted some new ones) … Possibly that was not the best idea and we should have waited.

**Comment by sphh** [comment]
Hi @jobisoft,
Have you found the time to look into the error I posted above?

**Comment by jobisoft** [comment]
Oh, you had not merged this in your repo? I removed my repository. I try to get a patch from this.

**Comment by jobisoft** [comment]
Can you send me the XPI you made from this?

**Comment by sphh** [comment]
Sure.

[tblatex.zip](https://github.com/protz/LatexIt/files/5512678/tblatex.zip)
Please rename it to `tblatex.xpi`

**Comment by jobisoft** [comment]
You have send me the legacy XUL version. Could you send me the version which you created from this PR? I do not have the files anymore as I thought you merged them.

**Comment by sphh** [comment]
You are right. Very strange, so I have no idea, what is going on here … Looks like I don't have it (anymore)

Can you see these two commits, you made?
* https://github.com/protz/LatexIt/pull/62/commits/b7ffcdc1f6df4b14208c27a3b0a0a3dc6f9bd457
* https://github.com/protz/LatexIt/pull/62/commits/445dfe6a1a045fe2032d1ca854cdee71ed3d544a

If you want, I could try to merge them into a local copy (most likely manually), zip it and upload it here.

**Comment by FMuro** [comment]
Any change that this gets reopen? I can understand that losing work is very irritating but sometimes these things happen. I still think it would be great to have this working in recent Thunderbird versions.

**Comment by jobisoft** [comment]
I am lost. Did this stall?

**Comment by sphh** [comment]
Well, yes, it sadly stalled on my side.

The reason is that I also have other programming to do and switching between two projects always takes time to become acquainted again. This is not helped that JavaScript is not the language of my choice and that I did not write the original code. This is ok to implement simple new features or find a bug, but the conversion to the new API need a bit more. Said that, at the moment I put the emphasis onto the other project.

I also would find it sad, if that extension would not survive the switch to the new API. That's why I put a lot of effort into fixing bugs and making it (IMHO) better and even offered to work on the conversion to the new API. With the help of @jobisoft, the add-on has proceeded to step 2 and runs on TB 78 with most features working. If I remember correctly, some features has still to be ported and tested. Any input here is highly appreciated! @FMuro?

**Comment by jobisoft** [comment]
I think I closed this issue because it appeared that another issue is covering the upgrade process. But I cannot really tell anymore. What is the status? Did we recover the lost pull request?

**Comment by AndrewCSQ** [comment]
Just wanted to chime in that I'm using the mailextension branch by @jobisoft and others and it works well enough for me on Thunderbird 78. Hopefully a final version makes it to publication (but I understand that dev time for a hobbyist project like this is rare), but thanks so much for the existing work!

**Comment by protz** [comment]
@jobisoft should we just release something sub-standard right now that barely works? I'm having a hard time figuring out where the branches are and what diff I should be looking at... any help much appreciated... thanks!

**Comment by sphh** [comment]
If I remember correctly, the basics are there, but the configuration is not working yet (but it's too long, when I worked on this and then I had to switch to my real job).

I am more than happy for anyone to pick up where I left and finish this!!!

**Comment by jobisoft** [comment]
I put this on my todo list for  ext week.

**Pull request closed without merging**
