### PR TITLE
Add quotation marks around file names with spaces

### PR DESCRIPTION
**Pull request by sphh**
@protz: This is a quick impromptu fix for #74 and is not tested at all (I cannot do it at the moment, sorry).

### CODE REVIEW

**Comment by sphh** [comment]
@protz: Finally I managed to test it on a Linux system, where it works now, but I don't have spaces in the path. It is **not** tested on Windows system or any other system having spaces in paths.

**Comment by protz** [comment]
I'd like to see some testing on windows before we merge a tentative fix. Does anyone have a test setup for windows?

**Comment by stevem6** [comment]
I tested in Windows 10, 64-bit but, as you'll see from my comments in #74, sanitize_path doesn't seem to help when running dvipng.exe in a shell.

**Comment by sphh** [comment]
Please see my comment https://github.com/protz/LatexIt/issues/74#issuecomment-782315986!

**Comment by sphh** [comment]
@protz Finally @stevem6 has figured out the problem. A description can be seen here: https://github.com/protz/LatexIt/issues/74#issuecomment-782931399

I am afraid, we have to do without the alignment feature on Windows, if we are not prepared to install a batch file. At least until `nsIProcess` is becoming grown up and enables us to read the standard output of a command. It's most unfortunate, that the shortcomings of Thunderbird's JavaScript and of Microsoft Windows are culminating in this case.

I believe, this PR can be closed now.

Before I start on a new PR, where this feature is removed on Windows systems: What is your opinion about a batch file? LatexIt! could write a temporary batch file, which can be called without `cmd.exe /C`. The batch file would call `dvipng` and redirects its output into the temporary depth file. That might be even less complicated than changing the call to `dvipng` inside of LatexIt!.

What do you think? Do you have any other idea, how to solve this without making it too complicated.

**Pull request closed without merging**
