### PR TITLE
Update to be compatible with TB60

### PR DESCRIPTION
**Pull request by indigestion**
Followed the details found within Mozilla's add-on guide for Thunderbird 57 - 60 [https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57](https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57).

### CODE REVIEW

**Comment by MaharishiCanada** [comment]
Tried to manually install tblatex-0.6.5.xpi in Thunderbird 60.2.1 in Ubuntu 18.04 and it replied "This add-on could not be installed because it appears to be corrupt."

**Comment by MaharishiCanada** [comment]
OK, I got this error message when I tried "install add-on from file" and picked the file tblatex-0.6.5.xpi. However, I followed the instruction "Alternatively, you can create a file named "tblatex@xulforum.org" in your extensions/ directory with a single line containing the path to this folder." and this worked.

**Comment by marmistrz** [comment]
Thanks a lot!!!

Works for me by installing from xpi (Arch Linux) but I needed to manually set the imagemagick security policy to allow PS output.

**Comment by chrisjudge** [comment]
@indigestion. Upon trying to install tblatex-0.6.6.xpi, I am getting error message "This add-on can not be installed because it appears to be corrupt". TB 60.3.3 on Mac High Sierra. Thanks for your work on this!

**Comment by protz** [comment]
Thanks for the pull request! Let me take a look at this and review.

**Comment by MaharishiCanada** [comment]
@crisjudge, it's only the file in the bin directory that is "corrupted". If you download the repo and execute make, the new compiled file will work. It did in my case.

**Comment by MaharishiCanada** [comment]
@marmistrz, I confirm that I had the same issue, but it existed before TB 60. It's not related to this patch.

**Comment by indigestion** [comment]
I am stumped. I tested adding the file to TB60 on Windows 10 and two computers running Arch Linux, and they all had no issues. Seems like something is up with TB60 on Mac and Ubuntu. I'm having trouble replicating the corrupt file and I don't have those platforms to test on.

**Comment by indigestion** [comment]
If you have a corrupt file, can you check the file integrity using md5sum or sha256sum?
**tblatex-0.6.5.xpi**
MD5: 9de1b14797d8101f260edbb432e245e4 
SHA256: a5e8398b19e7663ccca41011b77c3599f1cce7b9141f4239a150c5df08b092b7 

**tblatex-0.6.6.xpi**
MD5: 362180454a03c887f04ac85ea7de31d0
SHA256: 4b00c5c401579896dd7e75a4161d7a1b26348befec91bb6ea13b5ef0baa8b3bb

**Comment by MaharishiCanada** [comment]
@indigestion, I had this corrupted message with the first version in  https://github.com/indigestion/LatexIt/tree/master/bin . I did not try the second version.  Anyway, it's not a big deal, because when I compiled the file myself on Ubuntu, it worked. It's not the code, but the way it was compiled that created the issue.

**Comment by MaharishiCanada** [comment]
@indigestion, for some reason, the file I get  with "save  link as ..."  or with "wget https://github.com/indigestion/LatexIt/tree/master/bin/tblatex-0.6.5.xpi", both, have the same incorrect md5sum.  If, instead, I clone the entire repository, then I get the correct md5sum.   I am not expert enough about these download issues to understand why.

**Comment by MaharishiCanada** [comment]
@indigestion, for some reason, the file I get with "save link as ..." or with "wget https://github.com/indigestion/LatexIt/tree/master/bin/tblatex-0.6.5.xpi", both, have an incorrect md5sum. If, instead, I clone the entire repository, then I get the correct md5sum. I am not expert enough about these download issues to understand why. I thought wget was a faithful way to download a file.

**Comment by protz** [comment]
I believe you're just getting the HTML page you'd be getting if you were 
to click on that link.

Try 
https://github.com/indigestion/LatexIt/blob/master/bin/tblatex-0.6.5.xpi?raw=true 
instead?

**Comment by MaharishiCanada** [comment]
Yes, it works.   OK, I understand  now. If you are directly on the web page  https://github.com/indigestion/LatexIt/blob/master/bin, you need to click on the link  and then you have access to the raw file. Or you add ?raw=true, if you use directly the link.   I just did not understand how the repository works.  Sorry!

**Comment by chrisjudge** [comment]
Thanks to all!

**Pull request merged**
