### PR TITLE
Check for preview LaTeX package

### PR DESCRIPTION
**Pull request by sphh**
- Check for inclusion of "preview" package in LaTeX template (Bug #63).
- Added a do-not-delete note to the template regarding "\usepackage[active]{preview}".
- Added more aggressive error messages for severe errors.
- Tiny improvements in error messages.

I also added alert messages for more severe errors. Are these A Good Idea?

### CODE REVIEW

**Comment by protz** [comment]
This looks good but I'm afraid that if anything is wrong the user will get alert after alert which might turn out to be very irritating. Are you afraid the user doesn't get the message? It might be better to append everything to the log, maybe in red, so that the user can see everything that's wrong...?

@jobisoft might also flag that at addon review-time

**Comment by sphh** [comment]
Well my understanding is, that the function `run_latex()` exits, if it found an unrecoverable error, in which case the alert is displayed. If will be displayed again at a new run of Latex It!, until the error is sorted. My changes only affect critical errors, where no output .png is produced.

When checking for the `preview` LaTeX package, the behaviour is a bit different: Latex It! will continue, despite the error. And yes, at the next run, it will be displayed again. This might annoy some very advanced users who do not use the `preview` package. If this is a problem (and this alert message should be kept) I can think of two possible solutions:
1. Add an option to the configuration dialog to switch off this check.
2. Add a magic token, e.g. `% -*- no-check-for-preview-package -*-` to the template, which switches off this particular check.

Which part might @jobisoft flag?

**Comment by jobisoft** [comment]
I would flag something only, if it makes TB unusable, like an alert-box-loop and no way to exit the application. There are however nicer ways to inform the user about issues.

A nice way is the (WebExtension) notification API. That does not need user interaction, as it goes away on its own after a few seconds.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications

You need to add the "notifications" permissions. Example:
https://thunderbird.topicbox.com/groups/addons/T576f843ea846049c-M5089be9aa6f0d8da613814fa/notification-api-proposal

There is also a more complex legacy equivalent: notification box.

**Comment by sphh** [comment]
I just updated my previous comment, because the original did not give the reasons for the alert box …

Thanks, @jobisoft. But we are still a bit away from Latex It! being a WebExtension. We recently had some bug reports (some of them private), where the users where wondering, why the bitmap was in a strange place, so we thought it a good idea, to inform the user, that s/he has to modify their settings.

I agree with you, that as soon as Latex It! becomes a WebExtension, we should use this API. Is it worth at the moment to replace the few alert boxes showing fundamental errors with notification boxes? If it's easy, I might have a go … (an example would be highly appreciated, though)

**Comment by jobisoft** [comment]
> Thanks, @jobisoft. But we are still a bit away from Latex It! being a WebExtension. We recently had some bug reports (some of them private), where the users where wondering, why the bitmap was in a strange place, so we thought it a good idea, to inform the user, that s/he has to modify their settings.

You are not :-) After my conversion you are (!) a WebExtension and you can use WebExtension features. The concept here is as follows: The WL api gives you the messenger object in your injector script, where you can use it or push it into a JSM or a variable inside your encapsulated object in the window scope and instead of calling the alert, you call the notification.

**Comment by sphh** [comment]
Ok, ok, in your view, we might be already there, but my problem is, that I still don't grasp the concept yet (have I alread said, that I don't have much understanding of developing TB add-ons, but only started here to help removing some bugs which annoyed me :-o )

IMHO we should push that bug fix out quite soon to keep customers happy after the update. So I might consider removing all the additional `alert()` messages, but only leave that one handling the missing LaTeX package as a quick'n'dirty fix.

Then we have time to finish that conversion.

**Comment by jobisoft** [comment]
Yes, I did not intend to ask you to change that now. Sorry if I made that impression. I merely wanted to show you that you are in a hybrid state, where you can use features from both worlds.

If you need help, or have general question, you can contact me directly via john-at-thunderbird.net or via our add-on developer support channels:
https://developer.thunderbird.net/add-ons/community

**Comment by sphh** [comment]
No, I did not get this impression at all. Don't worry!

I might take up your generous offer.

This was just a general remark up for discussion. In the end it's @protz who has to decide, what he wants in his add-on, so this remark was more directed into his general direction. @protz, what do you think: Should it stay or should it go (but the alert about the missing `preview` LaTeX package)?

**Comment by protz** [comment]
Thanks to both of you for a great discussion.

I would keep the alert for the preview error (and abort) -- since it's likely that existing users, in the process of upgrading, might no longer pay very much attention to the "latexit report box" since they have done the configuration before. So an alert in their face will force them to act.

I would vote for the other errors to only remain in the "latexit report box" without an alert, because if the user is trying to fiddle with settings to get things right, too many alerts might prove frustrating.

@sphh what do you think?

**Comment by sphh** [comment]
Ok, no problem. I had the novice user in mind, who tried to get this beast going and run into the problem of wrong paths (despite that excellent first-run facilities).

May I suggest the following: Executables not found are alerted to the user with this not-to miss alert box, errors occurring, because something is wrong in the LaTeX contents, goes into the "latexit report box" (so no changes here).

As for the missing `preview` package: Do you really want to abort the insertion of a .png file, if that package is missing? Or do you want to proceed – after showing that alert box – inserting the (most likely wrong and misaligned) .png file?

**Comment by protz** [comment]
> May I suggest the following: Executables not found are alerted to the user with this not-to miss alert box, errors occurring, because something is wrong in the LaTeX contents, goes into the "latexit report box" (so no changes here).

Deal!

> As for the missing preview package: Do you really want to abort the insertion of a .png file, if that package is missing? Or do you want to proceed – after showing that alert box – inserting the (most likely wrong and misaligned) .png file?

The results seemed incredibly bad, with an overflow and an image that was way too big. So I'd rather abort rather than insert something that we know for sure is going to cause confusion.

**Comment by sphh** [comment]
We are not at a bazaar! ;-) It's your add-on, so no haggling here and you decide what is going in and what better not!!

I run out of ideas, so what I am concerned, please feel free to merge and publish this as an update on Thunderbird's add-on page.

Please update the `Changelog`, since I left the version number unidentified as `X.Y.Z`. Nor have I updated any manifest or `README`. The typo / bug you spotted, isn't included in the Changelog. I also left some space for the changes from 0.7.1 to 0.7.2 because I don't know what these were.

**Comment by protz** [comment]
> We are not at a bazaar! ;-) It's your add-on, so no haggling here and you decide what is going in and what better not!!

Indeed, but since you're proposing the changes and taking on the burden of implementing the bug fixes, you should have a say in the matter.

I'll do a release today and then we can try to figure out what's going on with Windows.

Cheers,

Jonathan

**Pull request merged**
