### PR TITLE
use WL API

### PR DESCRIPTION
**Pull request by jobisoft**
rebased against current master
- fix reported debug error in main.js
- works with installed latex
- added small hack to wait till editor is loaded (main.js: on_load)

known bugs:
- result from file picker in options dialog is not saved, it has to be manually "edited" to be seen by the preferenceBindings.js script.

### CODE REVIEW

**Comment by jobisoft** [comment]
grafik

**Comment by sphh** [comment]
Danke schön!!

Thanks also for adding the missing `}`.

I tried it a bit (but not extensively). The only problem I encountered, is, that `Latex It` disappeared from the `☰ > Add-ons` menu … How do I get to the configuration? If I filter for `tblatex` in the error console, I draw a blank.

**Comment by jobisoft** [comment]
In TB78 that menu is no longer populated, so the WL currently does not support it. What the WL does is adding it to the "old" tools menu:

grafik

In TB78 that menu has been removed as well but the WL API adds it back. That is why in TB68 it is there twice. But as the WL is not intended for TB68 (only during the first upgrade steps) I did not spend too much time on that.

What I try to achieve in the end is to add it to the "new" options location for WebExtensions, which is here:

grafik

But I have failed so far.

**Comment by sphh** [comment]
Thanks for the explanation. I had the top menu disabled, so I could not find it, because it does not appear in the `:☰ > Tools` menu. Would it be possible to put it also into this menu?

BTW in the English version, these two menus have different names: `Add-on Options` and `Add-on Preferences` …

Regarding the result from the file picker not saved: I observed a similar behaviour on the legacy add-on. I have a branch, where I can reset the LaTeX template in the last text entry box in the options dialog with the push of a button. I insert the default text programmatically, but is not saved. Only after making any edit, it will get saved. Are these problems related?

**Comment by sphh** [comment]
I tested a couple of scenarios and all of them work.

May I summarize the open issues:
- result from file picker in options dialog is not saved, it has to be manually "edited" to be seen by the preferenceBindings.js script. The same problem probably occurs when replacing the LaTeX template with the default one (but this is not yet officially implemented).
- The configuration menu does not appear in `☰ > Tools`, just in the `Menu bar > Tools` submenu.

What would be the next step?

**Comment by jobisoft** [comment]
> May I summarize the open issues:
> 
>     * result from file picker in options dialog is not saved, it has to be manually "edited" to be seen by the preferenceBindings.js script. The same problem probably occurs when replacing the LaTeX template with the default one (but this is not yet officially implemented).

Could be solved by getting rid of preferenceBindigs.js and manually load and save options. 

>     * The configuration menu does not appear in `☰ > Tools`, just in the `Menu bar > Tools` submenu.
> 
This will only work if TB78 will make that the default location for add-on options again. Nothing the WL API should take care of on its one.

> 
> What would be the next step?

I suggest to ignore the issue with preferences for now. Create a dedicated TB78 branch, merge this and do the last step of the update: https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-Finalizing

After this runs in TB78, tackle the preference issue. Either by fixing it, or by doing this follow-up update and replace prefBranch usage by local storage: https://github.com/thundernest/addon-developer-support/wiki/Tutorial:-Move-add-on-settings-from-nsIPrefBranch-to-local-storage

**Comment by sphh** [comment]
Hurray! I sent my first email with LaTeX inserted with TB 78!

I followed https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-Finalizing and converted all `.xul` to `.xhtml`, updated the code to use them and changed `manifest.json`. Here is a screenshot:
Screenshot from 2020-11-11 15-43-47

- You certainly have spotted, that the text on the `Latex It` button is not correctly aligned vertically.
- It also lost part of its functionality: The legacy button had the following features:
  - Clicking on the button, invoked to run `Latex It!`.
  - A middle click on the button undid the latest run.
  - The button had a drop-down menu, opened by clicking onto the down-arrow.

Now it lost the down-area and clicking onto the button opens the drop-down menu. Can you please point me into the right direction, how to get this features back (and how to corretly align the text vertically). Thanks.

At the moment I am trying to follow this tutorial: https://github.com/thundernest/addon-developer-support/wiki/Tutorial:-Move-add-on-settings-from-nsIPrefBranch-to-local-storage, but I am still struggling. How would I fix it (your first suggestion)?

**Comment by jobisoft** [comment]
Is your current work somewhere? Could you not merge this somewhere, so we could collaborate on the TB78 branch? 

In TB78 menu buttons are custom elements, you need to add an "is="toolbarbutton-menu-button".
Example from tb source: https://searchfox.org/comm-central/source/calendar/base/content/dialogs/calendar-summary-dialog.xhtml#74

I believe this must go in your messengercompose.js, but I probably cannot point to the correct line as my code differs from yours.

**Comment by sphh** [comment]
Hi @jobisoft,

I finally got around to open a new branch 'mailextension', pulled this request into it and added my work so far.

With your help from https://github.com/protz/LatexIt/pull/79#issuecomment-725601368 I got the toolbar button to work (again). A simple fix, if you know what to do… Thank you so much!

So what is missing, is the preferences issue. I went with your second suggestion (https://github.com/thundernest/addon-developer-support/wiki/Tutorial:-Move-add-on-settings-from-nsIPrefBranch-to-local-storage), but I am still struggling a bit. I'll keep you updated.

**Comment by jobisoft** [comment]
Great news! Do you want me to look over it on monday? Or do you have a question? You can find me on our matrix chat channel:
https://chat.mozilla.org/#/room/#tb-addon-developers:mozilla.org

**Pull request merged**
